### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by ryuhangyeong**
### Description

fix typo

PRs can be split if there are too many changes.

### CODE REVIEW

**Comment by qmhc** [comment]
Thanks for your PR. I think make more sense to keep typo fix together to reduce commit count.

**Comment by ryuhangyeong** [comment]
@qmhc

> Unless they will change the exported APIs.

Are you saying that if you change an exported API (e.g. `isItemDisbaled`), you should exclude it from that modification and post a separate PR?

**Comment by qmhc** [comment]
The judging criterion is whether they are exported in `index.ts` of each component (or root `index.ts`).

Those returns in components' setup method (e.g. isItemDisbaled) most are not public APIs (some are public and documented).

**Comment by ryuhangyeong** [comment]
@qmhc Done!

That PR only covered **typos**.

I'll make a separate PR to fix 'isLeepYear' and 'TimelinkItemType' later.

**Comment by qmhc** [comment]
LGTM. Thanks for your hard works!

**Review by qmhc — APPROVED** [review]

**Pull request merged**
