### PR TITLE
Create ar-EG locale

### PR DESCRIPTION
**Pull request by ahmedoashery**

### CODE REVIEW

**Comment by qmhc** [comment]
Thanks for your contribution.

Are the months and weeks same to English ? Just a question for me.

**Comment by ahmedoashery** [comment]
hi, hope  you well
thanks alot for this hard work 
months and weeks are ok and common to be in english

**Comment by qmhc** [comment]
Hi, you should merge #451 #452 #453 #454 into this PR instead of creating multiple PRs for one feature.

**Comment by ahmedoashery** [comment]
created new pull request with all changes

**Pull request closed without merging**
