### PR TITLE
chore: fix internal typos

### PR DESCRIPTION
**Pull request by ryuhangyeong**
### Description

fix internal typos

### CODE REVIEW

**Comment by qmhc** [comment]
Also a same `mechine` typo in `docs/en-US/guide/development-guide.md`. Could you fix it too?

**Comment by ryuhangyeong** [comment]
@qmhc Sure! In addition, a few more typos were found and reflected.

**Review by qmhc — APPROVED** [review]

**Comment by qmhc** [comment]
Good job!

**Comment by ryuhangyeong** [comment]
@qmhc Thanks~

**Pull request merged**
